### ISSUE TITLE
Add user guide

### ISSUE THREAD

**Issue by maartyman** [SolidLabResearch/solid-watch-party#40]
Add a step-by-step user guide to the top of the readme for users that want to use the demo. (make it very basic, so everyone can do it)

1: go to https://solidlabresearch.github.io/solid-watch-party/
2: login using
 - your solid pod
 - a test pod: oicdissuer: https://pod.playground.solidlab.be/ ; webid: https://pod.playground.solidlab.be/user1/profile/card#me ; email: user1@pod.playground.solidlab.be ; password: user1 
 - your own test pod: https://pod.playground.solidlab.be/.account/login/password/register/

2.1: enter oicd issuer
2.2: enter email and password
2.3: press authorize
3: create room
3: invite people

**Comment by eliasnijs** [comment]
In wiki, reference it in README
